/** بيانات السور الـ 114 الكاملة */
export interface Surah {
  n: number;       // رقم السورة
  a: string;       // الاسم العربي
  e: string;       // الاسم الإنجليزي
  trans: string;   // الترجمة
  t: "makki" | "madani"; // مكية/مدنية
  v: number;       // عدد الآيات
}

export const SURAHS: Surah[] = [
  { n: 1, a: "الفاتحة", e: "Al-Fatihah", trans: "The Opening", t: "makki", v: 7 },
  { n: 2, a: "البقرة", e: "Al-Baqarah", trans: "The Cow", t: "madani", v: 286 },
  { n: 3, a: "آل عمران", e: "Aal-E-Imran", trans: "The Family of Imran", t: "madani", v: 200 },
  { n: 4, a: "النساء", e: "An-Nisa", trans: "The Women", t: "madani", v: 176 },
  { n: 5, a: "المائدة", e: "Al-Ma'idah", trans: "The Table", t: "madani", v: 120 },
  { n: 6, a: "الأنعام", e: "Al-An'am", trans: "The Cattle", t: "makki", v: 165 },
  { n: 7, a: "الأعراف", e: "Al-A'raf", trans: "The Heights", t: "makki", v: 206 },
  { n: 8, a: "الأنفال", e: "Al-Anfal", trans: "The Spoils of War", t: "madani", v: 75 },
  { n: 9, a: "التوبة", e: "At-Tawbah", trans: "The Repentance", t: "madani", v: 129 },
  { n: 10, a: "يونس", e: "Yunus", trans: "Jonah", t: "makki", v: 109 },
  { n: 11, a: "هود", e: "Hud", trans: "Hud", t: "makki", v: 123 },
  { n: 12, a: "يوسف", e: "Yusuf", trans: "Joseph", t: "makki", v: 111 },
  { n: 13, a: "الرعد", e: "Ar-Ra'd", trans: "The Thunder", t: "madani", v: 43 },
  { n: 14, a: "إبراهيم", e: "Ibrahim", trans: "Abraham", t: "makki", v: 52 },
  { n: 15, a: "الحجر", e: "Al-Hijr", trans: "The Rocky Tract", t: "makki", v: 99 },
  { n: 16, a: "النحل", e: "An-Nahl", trans: "The Bee", t: "makki", v: 128 },
  { n: 17, a: "الإسراء", e: "Al-Isra", trans: "The Night Journey", t: "makki", v: 111 },
  { n: 18, a: "الكهف", e: "Al-Kahf", trans: "The Cave", t: "makki", v: 110 },
  { n: 19, a: "مريم", e: "Maryam", trans: "Mary", t: "makki", v: 98 },
  { n: 20, a: "طه", e: "Ta-Ha", trans: "Ta-Ha", t: "makki", v: 135 },
  { n: 21, a: "الأنبياء", e: "Al-Anbiya", trans: "The Prophets", t: "makki", v: 112 },
  { n: 22, a: "الحج", e: "Al-Hajj", trans: "The Pilgrimage", t: "madani", v: 78 },
  { n: 23, a: "المؤمنون", e: "Al-Mu'minun", trans: "The Believers", t: "makki", v: 118 },
  { n: 24, a: "النور", e: "An-Nur", trans: "The Light", t: "madani", v: 64 },
  { n: 25, a: "الفرقان", e: "Al-Furqan", trans: "The Criterion", t: "makki", v: 77 },
  { n: 26, a: "الشعراء", e: "Ash-Shu'ara", trans: "The Poets", t: "makki", v: 227 },
  { n: 27, a: "النمل", e: "An-Naml", trans: "The Ant", t: "makki", v: 93 },
  { n: 28, a: "القصص", e: "Al-Qasas", trans: "The Stories", t: "makki", v: 88 },
  { n: 29, a: "العنكبوت", e: "Al-Ankabut", trans: "The Spider", t: "makki", v: 69 },
  { n: 30, a: "الروم", e: "Ar-Rum", trans: "The Romans", t: "makki", v: 60 },
  { n: 31, a: "لقمان", e: "Luqman", trans: "Luqman", t: "makki", v: 34 },
  { n: 32, a: "السجدة", e: "As-Sajdah", trans: "The Prostration", t: "makki", v: 30 },
  { n: 33, a: "الأحزاب", e: "Al-Ahzab", trans: "The Confederates", t: "madani", v: 73 },
  { n: 34, a: "سبأ", e: "Saba", trans: "Sheba", t: "makki", v: 54 },
  { n: 35, a: "فاطر", e: "Fatir", trans: "The Originator", t: "makki", v: 45 },
  { n: 36, a: "يس", e: "Ya-Sin", trans: "Ya-Sin", t: "makki", v: 83 },
  { n: 37, a: "الصافات", e: "As-Saffat", trans: "Those Ranged in Ranks", t: "makki", v: 182 },
  { n: 38, a: "ص", e: "Sad", trans: "Sad", t: "makki", v: 88 },
  { n: 39, a: "الزمر", e: "Az-Zumar", trans: "The Groups", t: "makki", v: 75 },
  { n: 40, a: "غافر", e: "Ghafir", trans: "The Forgiver", t: "makki", v: 85 },
  { n: 41, a: "فصلت", e: "Fussilat", trans: "Explained in Detail", t: "makki", v: 54 },
  { n: 42, a: "الشورى", e: "Ash-Shura", trans: "The Consultation", t: "makki", v: 53 },
  { n: 43, a: "الزخرف", e: "Az-Zukhruf", trans: "The Gold Adornments", t: "makki", v: 89 },
  { n: 44, a: "الدخان", e: "Ad-Dukhan", trans: "The Smoke", t: "makki", v: 59 },
  { n: 45, a: "الجاثية", e: "Al-Jathiyah", trans: "The Kneeling", t: "makki", v: 37 },
  { n: 46, a: "الأحقاف", e: "Al-Ahqaf", trans: "The Wind-Curved Sandhills", t: "makki", v: 35 },
  { n: 47, a: "محمد", e: "Muhammad", trans: "Muhammad", t: "madani", v: 38 },
  { n: 48, a: "الفتح", e: "Al-Fath", trans: "The Victory", t: "madani", v: 29 },
  { n: 49, a: "الحجرات", e: "Al-Hujurat", trans: "The Rooms", t: "madani", v: 18 },
  { n: 50, a: "ق", e: "Qaf", trans: "Qaf", t: "makki", v: 45 },
  { n: 51, a: "الذاريات", e: "Adh-Dhariyat", trans: "The Winnowing Winds", t: "makki", v: 60 },
  { n: 52, a: "الطور", e: "At-Tur", trans: "The Mount", t: "makki", v: 49 },
  { n: 53, a: "النجم", e: "An-Najm", trans: "The Star", t: "makki", v: 62 },
  { n: 54, a: "القمر", e: "Al-Qamar", trans: "The Moon", t: "makki", v: 55 },
  { n: 55, a: "الرحمن", e: "Ar-Rahman", trans: "The Most Merciful", t: "madani", v: 78 },
  { n: 56, a: "الواقعة", e: "Al-Waqi'ah", trans: "The Inevitable", t: "makki", v: 96 },
  { n: 57, a: "الحديد", e: "Al-Hadid", trans: "The Iron", t: "madani", v: 29 },
  { n: 58, a: "المجادلة", e: "Al-Mujadila", trans: "The Pleading Woman", t: "madani", v: 22 },
  { n: 59, a: "الحشر", e: "Al-Hashr", trans: "The Exile", t: "madani", v: 24 },
  { n: 60, a: "الممتحنة", e: "Al-Mumtahanah", trans: "The Examined", t: "madani", v: 13 },
  { n: 61, a: "الصف", e: "As-Saff", trans: "The Ranks", t: "madani", v: 14 },
  { n: 62, a: "الجمعة", e: "Al-Jumu'ah", trans: "Friday", t: "madani", v: 11 },
  { n: 63, a: "المنافقون", e: "Al-Munafiqun", trans: "The Hypocrites", t: "madani", v: 11 },
  { n: 64, a: "التغابن", e: "At-Taghabun", trans: "Mutual Disillusion", t: "madani", v: 18 },
  { n: 65, a: "الطلاق", e: "At-Talaq", trans: "Divorce", t: "madani", v: 12 },
  { n: 66, a: "التحريم", e: "At-Tahrim", trans: "The Prohibition", t: "madani", v: 12 },
  { n: 67, a: "الملك", e: "Al-Mulk", trans: "The Sovereignty", t: "makki", v: 30 },
  { n: 68, a: "القلم", e: "Al-Qalam", trans: "The Pen", t: "makki", v: 52 },
  { n: 69, a: "الحاقة", e: "Al-Haqqah", trans: "The Reality", t: "makki", v: 52 },
  { n: 70, a: "المعارج", e: "Al-Ma'arij", trans: "The Ascending Stairways", t: "makki", v: 44 },
  { n: 71, a: "نوح", e: "Nuh", trans: "Noah", t: "makki", v: 28 },
  { n: 72, a: "الجن", e: "Al-Jinn", trans: "The Jinn", t: "makki", v: 28 },
  { n: 73, a: "المزمل", e: "Al-Muzzammil", trans: "The Enshrouded", t: "makki", v: 20 },
  { n: 74, a: "المدثر", e: "Al-Muddaththir", trans: "The Cloaked", t: "makki", v: 56 },
  { n: 75, a: "القيامة", e: "Al-Qiyamah", trans: "The Resurrection", t: "makki", v: 40 },
  { n: 76, a: "الإنسان", e: "Al-Insan", trans: "Man", t: "madani", v: 31 },
  { n: 77, a: "المرسلات", e: "Al-Mursalat", trans: "Those Sent Forth", t: "makki", v: 50 },
  { n: 78, a: "النبأ", e: "An-Naba", trans: "The Tidings", t: "makki", v: 40 },
  { n: 79, a: "النازعات", e: "An-Nazi'at", trans: "Those Who Pull Out", t: "makki", v: 46 },
  { n: 80, a: "عبس", e: "Abasa", trans: "He Frowned", t: "makki", v: 42 },
  { n: 81, a: "التكوير", e: "At-Takwir", trans: "The Folding Up", t: "makki", v: 29 },
  { n: 82, a: "الانفطار", e: "Al-Infitar", trans: "The Cleaving", t: "makki", v: 19 },
  { n: 83, a: "المطففين", e: "Al-Mutaffifin", trans: "Defrauding", t: "makki", v: 36 },
  { n: 84, a: "الانشقاق", e: "Al-Inshiqaq", trans: "The Splitting", t: "makki", v: 25 },
  { n: 85, a: "البروج", e: "Al-Buruj", trans: "The Mansions of the Stars", t: "makki", v: 22 },
  { n: 86, a: "الطارق", e: "At-Tariq", trans: "The Morning Star", t: "makki", v: 17 },
  { n: 87, a: "الأعلى", e: "Al-A'la", trans: "The Most High", t: "makki", v: 19 },
  { n: 88, a: "الغاشية", e: "Al-Ghashiyah", trans: "The Overwhelming", t: "makki", v: 26 },
  { n: 89, a: "الفجر", e: "Al-Fajr", trans: "The Dawn", t: "makki", v: 30 },
  { n: 90, a: "البلد", e: "Al-Balad", trans: "The City", t: "makki", v: 20 },
  { n: 91, a: "الشمس", e: "Ash-Shams", trans: "The Sun", t: "makki", v: 15 },
  { n: 92, a: "الليل", e: "Al-Layl", trans: "The Night", t: "makki", v: 21 },
  { n: 93, a: "الضحى", e: "Ad-Duha", trans: "The Morning Hours", t: "makki", v: 11 },
  { n: 94, a: "الشرح", e: "Ash-Sharh", trans: "The Relief", t: "makki", v: 8 },
  { n: 95, a: "التين", e: "At-Tin", trans: "The Fig", t: "makki", v: 8 },
  { n: 96, a: "العلق", e: "Al-Alaq", trans: "The Clot", t: "makki", v: 19 },
  { n: 97, a: "القدر", e: "Al-Qadr", trans: "The Power", t: "makki", v: 5 },
  { n: 98, a: "البينة", e: "Al-Bayyinah", trans: "The Clear Proof", t: "madani", v: 8 },
  { n: 99, a: "الزلزلة", e: "Az-Zalzalah", trans: "The Earthquake", t: "madani", v: 8 },
  { n: 100, a: "العاديات", e: "Al-Adiyat", trans: "The Chargers", t: "makki", v: 11 },
  { n: 101, a: "القارعة", e: "Al-Qari'ah", trans: "The Striking Hour", t: "makki", v: 11 },
  { n: 102, a: "التكاثر", e: "At-Takathur", trans: "Competition", t: "makki", v: 8 },
  { n: 103, a: "العصر", e: "Al-Asr", trans: "Time", t: "makki", v: 3 },
  { n: 104, a: "الهمزة", e: "Al-Humazah", trans: "The Slanderer", t: "makki", v: 9 },
  { n: 105, a: "الفيل", e: "Al-Fil", trans: "The Elephant", t: "makki", v: 5 },
  { n: 106, a: "قريش", e: "Quraysh", trans: "Quraysh", t: "makki", v: 4 },
  { n: 107, a: "الماعون", e: "Al-Ma'un", trans: "Almsgiving", t: "makki", v: 7 },
  { n: 108, a: "الكوثر", e: "Al-Kawthar", trans: "Abundance", t: "makki", v: 3 },
  { n: 109, a: "الكافرون", e: "Al-Kafirun", trans: "The Disbelievers", t: "makki", v: 6 },
  { n: 110, a: "النصر", e: "An-Nasr", trans: "Divine Support", t: "madani", v: 3 },
  { n: 111, a: "المسد", e: "Al-Masad", trans: "The Palm Fiber", t: "makki", v: 5 },
  { n: 112, a: "الإخلاص", e: "Al-Ikhlas", trans: "Sincerity", t: "makki", v: 4 },
  { n: 113, a: "الفلق", e: "Al-Falaq", trans: "Daybreak", t: "makki", v: 5 },
  { n: 114, a: "الناس", e: "An-Nas", trans: "Mankind", t: "makki", v: 6 },
];

export const getSurah = (n: number): Surah | undefined => SURAHS[n - 1];
